export { LoginPage } from './LoginPage';
export { RegisterPage } from './RegisterPageCompact';
export { DashboardPage } from './DashboardPage';
export { AuthCallbackPage } from './AuthCallbackPage';
export { default as TermsOfServicePage } from './TermsOfServicePage';
export { default as PrivacyPolicyPage } from './PrivacyPolicyPage';
export { TurnosPage } from './TurnosPage';
export { CrearTurnoPage } from './CrearTurnoPage';
export { SociosPage } from './SociosPage';
export { default as ConfiguracionPage } from './ConfiguracionPage';
export { default as ConfiguracionPerfilPage } from './ConfiguracionPerfilPage';